apiVersion: apps/v1
kind: Deployment
metadata:
  name: ngrok-tunnel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ngrok
  template:
    metadata:
      labels:
        app: ngrok
    spec:
      containers:
      - name: ngrok
        image: ngrok/ngrok:latest
        args:
        - "http"
        - "--url=semibourgeois-subrectal-karry.ngrok-free.dev"
        - "samai-service:8080"
        env:
        - name: NGROK_AUTHTOKEN
          valueFrom:
            secretKeyRef:
              name: ngrok-secret
              key: token
